FROM jasonish/suricata:latest

# Utilisation de Suricata officielle, déjà bien optimisée
# Pas besoin d'installer d'outils additionnels
CMD ["suricata", "-i", "eth0", "-c", "/etc/suricata/suricata.yaml", "-v"]
