#!/bin/bash

echo "=== MISSION 1: Détection et réaction à un bruteforce SSH ==="
echo " "
echo "[1] Connectez-vous au conteneur fail2ban :"
echo "    docker exec -it fail2ban /bin/sh"
echo " "
echo "[2] Vérifiez les bans SSH actifs :"
echo "    fail2ban-client status sshd"
echo " "
echo "[3] Regardez le fichier des logs SSH :"
echo "    tail -f /var/log/auth.log"
echo " "
echo "[4] Identifiez une adresse IP source d'attaques."
echo " "
echo "[5] Faites un WHOIS sur l'IP pour voir d'où vient l'attaque :"
echo "    whois <IP>"
echo " "
echo "[6] Bloquez manuellement une IP si nécessaire :"
echo "    iptables -A INPUT -s <IP> -j DROP"
echo " "
echo "=== Objectif : Comprendre comment Fail2Ban détecte et bloque automatiquement ==="
